/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex2;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        Whale mobyDick = new Whale(1, "Moby Dick", Gender.MALE, "White", Species.UNKNOWN );
        User reporter = new User("cap-ahab", "Captain Ahab", "cahab@seaworld.com", Roles.REPORTER);
        Location newEngland = new Location(43.9654, 70.8227);
        LocationObservation mobyDickObservation =
                new LocationObservation(0,
                        reporter,
                        new Date(),
                        Species.UNKNOWN,
                        Direction.EAST,
                        "Sunny",
                        "thar she BLOWS!",
                        newEngland);

        ObservationRepository observations = new ObservationRepository();
        observations.add(mobyDickObservation);

        WhaleRepository whales = new WhaleRepository();
        whales.add(mobyDick);

    }
}
