/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.uvic.seng330.ex3;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class WhaleTests {
    private WhaleRepository whales;
    private Whale whale1;
    private Whale whale2;
    private Whale whale3;
    private Whale whale4;

    @BeforeEach
    void before() {
        whale1 = new Whale(5, "Moby Dick", Gender.MALE, "White", Species.UNKNOWN);
        whale2 = new Whale(0, "Sam", Gender.MALE, "Gray", Species.UNKNOWN);
        whale3 = new Whale(2, "Ralph", Gender.MALE, "Gray", Species.UNKNOWN);
        whale4 = new Whale(1, "Sam", Gender.MALE, "Gray", Species.UNKNOWN);

        whales = new WhaleRepository();
        whales.add(whale1);
        whales.add(whale2);
        whales.add(whale3);
        whales.add(whale4);
    }


    @Test
    void whale1IsGreater() {
        Whale.CompareById comparer = new Whale.CompareById();
        int x = comparer.compare(whale1, whale2);
        assertEquals(5, x);
    }

    @Test
    void searchById() {
        Whale result = whales.getById(2);
        assertNotEquals(null, result);
        assertEquals("Ralph", result.getName());

        Whale result2 = whales.getById(-1); // Negative test case
        assertEquals(null, result2);
    }

    @Test
    void searchByGender() {
        List<Whale> result = whales.getByGender(Gender.MALE);
        assertNotEquals(null, result);
        assertEquals(4, result.size());
    }

    @Test
    void searchBySpecies() {
        List<Whale> result = whales.getBySpecies(Species.UNKNOWN);
        assertNotEquals(null, result);
        assertEquals(4, result.size());
    }

    @Test
    void sortWhalesById() {
        whales.sortById();

        List<Whale> ans = new ArrayList();
        ans.add(whale2);
        ans.add(whale4);
        ans.add(whale3);
        ans.add(whale1);
        assertEquals(ans, whales.getWhales());
    }

    @Test
    void sortEmptyWhalesById() {
        // Test with empty whale repo
        WhaleRepository whales = new WhaleRepository();
        try {
            whales.sortById();
        } catch (Exception e) {
            fail();
        }
    }
}
